import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { MongoMemoryServer } from "mongodb-memory-server";

/**
 * True end-to-end coverage: real HTTP requests against the actual Hono `app`
 * (spec 01 §Council service), a real (in-process, hermetic) MongoDB, and demo
 * mode's real event pipeline — no mocks. `DEMO_SPEED` is cranked up so the
 * ~68s real-time fixture replay finishes in a few seconds; production
 * `pnpm demo` is unaffected (defaults to 1x, spec 09 §Demo mode).
 *
 * One shared MongoMemoryServer + one dynamic import for the whole file:
 * `mongodb-memory-server` downloads/locks a shared binary cache, so two
 * instances starting in parallel (e.g. from two test files) race on it.
 * Env vars must be set before `../src/app.js` (and its transitive imports,
 * which read `process.env` once via config/env.ts) is ever imported — hence
 * the dynamic `import()` here, after `MONGODB_URI` points at the test server.
 *
 * Describe blocks run in declaration order within a file (vitest doesn't
 * parallelize tests inside one file by default), so the concurrency-cap test
 * runs first, before any other session exists — `activeSessions` in
 * session-runner.ts is module-level state shared across every test below.
 */

let mongod: MongoMemoryServer;
let app: typeof import("../src/app.js")["app"];
let closeDb: typeof import("../src/db/client.js")["closeDb"];

const EXPECTED_EVENT_COUNT = 53; // fixtures/golden-session.jsonl, generated by scripts/generate-golden-fixture.ts

async function waitForStatus(
  sessionId: string,
  status: string,
  timeoutMs = 15_000,
): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    const res = await app.request(`/sessions/${sessionId}`);
    const body = (await res.json()) as { status: string };
    if (body.status === status) return;
    if (Date.now() > deadline) {
      throw new Error(`timed out waiting for session ${sessionId} to reach '${status}' (was '${body.status}')`);
    }
    await new Promise((r) => setTimeout(r, 25));
  }
}

async function pollEvents(sessionId: string, minCount: number, timeoutMs = 15_000): Promise<any[]> {
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    const res = await app.request(`/sessions/${sessionId}/events`);
    const body = (await res.json()) as { events: any[] };
    if (body.events.length >= minCount) return body.events;
    if (Date.now() > deadline) {
      throw new Error(`timed out waiting for ${minCount} events (got ${body.events.length})`);
    }
    await new Promise((r) => setTimeout(r, 25));
  }
}

interface ParsedSSEEvent {
  event: string;
  id: string;
  data: any;
}

/** Reads SSE frames off a streaming Response until `expectedCount` are seen (or timeout),
 *  then cancels the reader — the server route only closes on client abort, never on its own. */
async function readSSEEvents(
  response: Response,
  expectedCount: number,
  timeoutMs = 15_000,
): Promise<ParsedSSEEvent[]> {
  const reader = response.body!.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  const events: ParsedSSEEvent[] = [];
  const deadline = Date.now() + timeoutMs;

  try {
    while (events.length < expectedCount) {
      if (Date.now() > deadline) {
        throw new Error(`timed out after ${events.length}/${expectedCount} SSE events`);
      }
      const { value, done } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const frames = buffer.split("\n\n");
      buffer = frames.pop() ?? "";
      for (const frame of frames) {
        if (!frame.trim()) continue;
        let eventType = "";
        let id = "";
        let data = "";
        for (const line of frame.split("\n")) {
          if (line.startsWith("event: ")) eventType = line.slice("event: ".length);
          else if (line.startsWith("id: ")) id = line.slice("id: ".length);
          else if (line.startsWith("data: ")) data += line.slice("data: ".length);
        }
        if (data) events.push({ event: eventType, id, data: JSON.parse(data) });
      }
    }
  } finally {
    await reader.cancel().catch(() => {});
  }
  return events;
}

beforeAll(async () => {
  mongod = await MongoMemoryServer.create();
  process.env.MONGODB_URI = mongod.getUri();
  process.env.COUNCIL_SERVICE_TOKEN = "";
  process.env.DEMO_MODE = "0";
  process.env.DEMO_SPEED = "20"; // ~68s fixture replay -> ~3.4s
  process.env.COST_CAP_USD = "0.50";
  process.env.WEB_ORIGIN = "http://localhost:3000";

  ({ app } = await import("../src/app.js"));
  const dbClient = await import("../src/db/client.js");
  closeDb = dbClient.closeDb;

  // Mirrors seed/setup-indexes.ts's standard indexes (spec 03 §Indexes) — the
  // real service depends on the sessions.dilemma text index existing (the
  // GET /sessions?q= search route), which a fresh test database doesn't have.
  const db = await dbClient.getDb();
  await db.collection("sessions").createIndex({ dilemma: "text" });
}, 60_000);

afterAll(async () => {
  await closeDb();
  await mongod.stop();
});

describe("concurrency cap (e2e)", () => {
  it("accepts at most 3 concurrent sessions and 429s the rest", async () => {
    const post = (dilemma: string) =>
      app.request("/sessions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ dilemma, demo: true }),
      });

    const responses = await Promise.all([
      post("concurrency check 1"),
      post("concurrency check 2"),
      post("concurrency check 3"),
      post("concurrency check 4"),
    ]);

    const statuses = responses.map((r) => r.status).sort();
    expect(statuses).toEqual([201, 201, 201, 429]);

    const rejected = responses.find((r) => r.status === 429)!;
    const body = (await rejected.json()) as { error: string };
    expect(body.error).toMatch(/council is in session/i);

    // Drain the 3 accepted background sessions before moving on — otherwise
    // they're still writing to the DB when `afterAll` tears it down.
    const accepted = await Promise.all(
      responses.filter((r) => r.status === 201).map((r) => r.json() as Promise<{ id: string }>),
    );
    await Promise.all(accepted.map(({ id }) => waitForStatus(id, "done")));
  }, 15_000);
});

describe("request validation (e2e)", () => {
  it("rejects a session request missing a dilemma with 400", async () => {
    const res = await app.request("/sessions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ demo: true }),
    });
    expect(res.status).toBe(400);
    const body = (await res.json()) as { error: string };
    expect(body.error).toBe("invalid request");
  });

  it("rejects non-JSON bodies with 400 rather than crashing", async () => {
    const res = await app.request("/sessions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: "not json at all",
    });
    expect(res.status).toBe(400);
  });

  it("404s a session id that doesn't exist", async () => {
    const res = await app.request("/sessions/00000000-0000-0000-0000-000000000000");
    expect(res.status).toBe(404);
  });
});

describe("session lifecycle (e2e)", () => {
  let sessionId: string;

  it("creates a demo session via POST /sessions", async () => {
    const res = await app.request("/sessions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ dilemma: "Should our startup switch to annual billing?", demo: true }),
    });
    expect(res.status).toBe(201);
    const body = (await res.json()) as { id: string };
    expect(body.id).toMatch(/^[0-9a-f-]{36}$/);
    sessionId = body.id;
  });

  it("replays the full fixture through the real event pipeline", async () => {
    const events = await pollEvents(sessionId, EXPECTED_EVENT_COUNT);
    expect(events).toHaveLength(EXPECTED_EVENT_COUNT);
    expect(events[0].type).toBe("session_started");
    expect(events[events.length - 1].type).toBe("session_done");
    // seq is strictly increasing and contiguous from 0 (spec 02 §Guarantees)
    events.forEach((e, i) => expect(e.seq).toBe(i));
  }, 20_000);

  it("GET /sessions/:id reports status done with the parsed council size", async () => {
    const res = await app.request(`/sessions/${sessionId}`);
    expect(res.status).toBe(200);
    const body = (await res.json()) as { status: string; councilSize: number };
    expect(body.status).toBe("done");
    expect(body.councilSize).toBe(4);
  });

  it("GET /sessions lists the finished session with orb data", async () => {
    const res = await app.request("/sessions");
    const body = (await res.json()) as { sessions: any[] };
    const found = body.sessions.find((s) => s.id === sessionId);
    expect(found).toBeDefined();
    expect(found.status).toBe("done");
    expect(found.orb.hues).toHaveLength(4);
    expect(found.orb.voteSplit.for).toHaveLength(4);
  });

  it("GET /sessions?q= finds it by dilemma text and excludes non-matches", async () => {
    const hit = await app.request("/sessions?q=annual");
    const hitBody = (await hit.json()) as { sessions: any[] };
    expect(hitBody.sessions.some((s) => s.id === sessionId)).toBe(true);

    const miss = await app.request("/sessions?q=zzz_no_such_dilemma_zzz");
    const missBody = (await miss.json()) as { sessions: any[] };
    expect(missBody.sessions.some((s) => s.id === sessionId)).toBe(false);
  });

  it("SSE stream replays the full backlog for a finished session", async () => {
    const res = await app.request(`/sessions/${sessionId}/stream`, {
      headers: { "Last-Event-ID": "-1" },
    });
    expect(res.status).toBe(200);
    const events = await readSSEEvents(res, EXPECTED_EVENT_COUNT);
    expect(events).toHaveLength(EXPECTED_EVENT_COUNT);
    expect(events[0].event).toBe("session_started");
    expect(events[events.length - 1].event).toBe("session_done");
  }, 20_000);

  it("SSE stream resumes from Last-Event-ID, sending only events after it", async () => {
    const resumeFrom = 40;
    const res = await app.request(`/sessions/${sessionId}/stream`, {
      headers: { "Last-Event-ID": String(resumeFrom) },
    });
    const events = await readSSEEvents(res, EXPECTED_EVENT_COUNT - resumeFrom - 1);
    expect(events.every((e) => Number(e.id) > resumeFrom)).toBe(true);
    expect(events[events.length - 1].event).toBe("session_done");
  }, 20_000);
});

describe("a fresh live-in-flight session (e2e)", () => {
  it("streams events as they happen, then resumes mid-flight from a partial position", async () => {
    const createRes = await app.request("/sessions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ dilemma: "Mid-flight resume check", demo: true }),
    });
    const { id } = (await createRes.json()) as { id: string };

    // Wait for a partial position, then resume from there and confirm nothing
    // before it is redelivered, and the stream still reaches session_done.
    const partial = await pollEvents(id, 10);
    const resumeFrom = partial[partial.length - 1].seq;

    const res = await app.request(`/sessions/${id}/stream`, {
      headers: { "Last-Event-ID": String(resumeFrom) },
    });
    const events = await readSSEEvents(res, EXPECTED_EVENT_COUNT - resumeFrom - 1, 20_000);
    expect(events.every((e) => Number(e.id) > resumeFrom)).toBe(true);
    expect(events[events.length - 1].event).toBe("session_done");
  }, 25_000);
});
